### ISSUE TITLE
Implement User JSON IO Handler

### ISSUE THREAD

**Issue by tahic-himzo** [tahic-himzo/interest-matcher#10]
AC in title

User-Model:
```
  User:
    type: object
    required:
      - userName
      - firstName
      - lastName
      - email
      - interests
    properties:
      userName:
        type: string
      firstName:
        type: string
      lastName:
        type: string
      email:
        type: string
      interests:
        type: array
        items:
          type: "string"
```
