### ISSUE TITLE
Introduce a User Model

### ISSUE THREAD

**Issue by tahic-himzo** [tahic-himzo/interest-matcher#15]
It should adhere to this spec:
```
definitions:
  User:
    type: object
    required:
      - userName
      - firstName
      - lastName
      - email
      - interests
    properties:
      userName:
        type: string
      firstName:
        type: string
      lastName:
        type: string
      email:
        type: string
      interests:
        type: array
        items:
          type: "string"
```
